(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  Script generated:  2017-12-05 00:58:48
  From session:  Amazon Login
  Captured on:  2017-12-05 00:57:01
  From server:  10190227160
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

DoubleClick "image0007"
Click (Image:"image0008", WaitFor:3.1)

TypeText "https://amazon.com",Return
waitfor 10
Click "HelloSigninAccountLists"
TypeText "vinaya",Backspace,"kumarcv.bly"
Click "image0010"
